# Generated by Django 5.0 on 2024-01-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('english_news', models.TextField()),
                ('ukrainian_news', models.TextField()),
                ('keywords', models.JSONField()),
                ('questions', models.JSONField()),
            ],
        ),
    ]
