# Generated by Django 5.0 on 2024-01-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.CharField(default='', max_length=10),
        ),
    ]
